import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

/* Link previews, on every page rather than just the homepage.
 *
 * Only /index.html had Open Graph tags and a canonical URL. The other 197
 * pages -- including the ~190 lesson pages a teacher actually shares -- had
 * none, so a lesson link posted into a school's Slack or into Google Classroom
 * previewed as a bare URL. That is precisely the moment the product is being
 * recommended by one teacher to another, and it looked broken.
 *
 * Generated by scripts/build-meta.py from each page's own <title> and
 * description, so there is no second copy of the content to drift.
 */

const SKIP_DIRS = new Set(['node_modules', '.git', 'lesson-format-kit', 'REVIEW', 'docs']);
// Never advertised to a crawler or a card scraper.
const SKIP_FILES = new Set([
  '404.html', 'admin.html', 'sandbox-export.html',
  /* learn.html is a redirect stub whose <title> is "Redirecting…" and whose
     hand-written canonical deliberately points at /curriculum.html. Generating
     a card for it would advertise a page that exists only to bounce you, and
     adding a second canonical pointing at itself told a crawler two
     contradictory things -- which is exactly what the generator did on its
     first run, and what it now refuses to do. */
  'learn.html',
]);

function pages() {
  const out = [];
  const walk = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (e.name.startsWith('.') || SKIP_DIRS.has(e.name)) continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) walk(full);
      else if (e.name.endsWith('.html') && !SKIP_FILES.has(e.name)) out.push(full);
    }
  };
  walk('.');
  return out;
}

const ALL = pages();

describe('every public page can be shared', () => {
  it('finds the pages', () => {
    expect(ALL.length).toBeGreaterThan(150);
  });

  for (const tag of [
    ['og:title', /<meta property="og:title" content="[^"]+"/],
    ['og:url', /<meta property="og:url" content="https:\/\/mypypath\.com[^"]*"/],
    ['og:image', /<meta property="og:image" content="https:\/\/[^"]+"/],
    ['twitter:card', /<meta name="twitter:card" content="summary"/],
    ['canonical', /<link rel="canonical" href="https:\/\/mypypath\.com[^"]*"/],
  ]) {
    it(`has ${tag[0]}`, () => {
      const missing = ALL.filter((p) => !tag[1].test(fs.readFileSync(p, 'utf8')));
      expect(missing).toEqual([]);
    });
  }
});

describe('the canonical URL points at the page it is on', () => {
  it('matches the file path for every page', () => {
    /* The failure this catches is the one a generated block makes easy: a
       copy-paste that leaves every lesson claiming to be /index.html, which
       tells a search engine the whole course is one page. */
    const wrong = [];
    for (const p of ALL) {
      const src = fs.readFileSync(p, 'utf8');
      const m = src.match(/<link rel="canonical" href="https:\/\/mypypath\.com(\/[^"]*)"/);
      if (!m) continue;
      const rel = p.replace(/^\.\//, '');
      const want = rel === 'index.html' ? '/' : `/${rel}`;
      if (m[1] !== want) wrong.push(`${p}: says ${m[1]}, is ${want}`);
    }
    expect(wrong).toEqual([]);
  });

  it('og:url agrees with the canonical', () => {
    const wrong = [];
    for (const p of ALL) {
      const src = fs.readFileSync(p, 'utf8');
      const c = src.match(/<link rel="canonical" href="([^"]+)"/);
      const o = src.match(/<meta property="og:url" content="([^"]+)"/);
      if (c && o && c[1] !== o[1]) wrong.push(`${p}: ${o[1]} vs ${c[1]}`);
    }
    expect(wrong).toEqual([]);
  });
});

describe('the generated block is safe to regenerate', () => {
  it('is fenced by markers on every page it wrote', () => {
    const generated = ALL.filter((p) => fs.readFileSync(p, 'utf8').includes('meta:begin'));
    expect(generated.length).toBeGreaterThan(150);
    for (const p of generated) {
      expect(fs.readFileSync(p, 'utf8'), p).toContain('meta:end');
    }
  });

  it('leaves the hand-written homepage tags alone', () => {
    /* index.html's tags predate the generator and are richer -- a bespoke
       description and a title written for the card. The generator skips any
       page with og: tags outside its own block rather than flattening them. */
    const home = fs.readFileSync('index.html', 'utf8');
    expect(home).not.toContain('meta:begin');
    expect(home).toContain('property="og:title"');
    expect(home).toContain('Follow the PyPath');
  });

  it('the card image is a real file, at the size the tags claim', () => {
    // A card pointing at a 404 previews worse than no card at all.
    expect(fs.existsSync('assets/img/og-card.png')).toBe(true);
    expect(fs.statSync('assets/img/og-card.png').size).toBeGreaterThan(1000);
  });
});

describe('the card title does not stutter', () => {
  it('drops a trailing site name, whichever separator was used', () => {
    /* Lesson titles end in "• PyPath" and page titles in "| PyPath". A card
       showing "Unit 1 • What Is Python • PyPath" above a site_name line
       already reading "PyPath" says it twice. */
    const bad = [];
    for (const p of ALL) {
      const m = fs.readFileSync(p, 'utf8')
        .match(/<meta property="og:title" content="([^"]+)"/);
      if (m && /[|•·—–-]\s*PyPath\s*$/.test(m[1])) bad.push(`${p}: ${m[1]}`);
    }
    expect(bad).toEqual([]);
  });

  it('but keeps the full title in the tab', () => {
    // The <title> is unchanged; only the card is trimmed.
    const lesson = fs.readFileSync('units/unit-1/what-is-python.html', 'utf8');
    expect(lesson).toMatch(/<title>[^<]*PyPath[^<]*<\/title>/);
  });
});

describe('lesson pages are articles, the rest are websites', () => {
  it('a lesson is og:type article', () => {
    const lesson = fs.readFileSync('units/unit-1/what-is-python.html', 'utf8');
    expect(lesson).toContain('<meta property="og:type" content="article" />');
  });

  it('a tool page is og:type website', () => {
    expect(fs.readFileSync('quiz.html', 'utf8'))
      .toContain('<meta property="og:type" content="website" />');
  });
});

describe('a page that deliberately points elsewhere is left alone', () => {
  it('learn.html keeps exactly one canonical, and it is not itself', () => {
    const src = fs.readFileSync('learn.html', 'utf8');
    const all = src.match(/rel="canonical"/g) || [];
    expect(all).toHaveLength(1);
    expect(src).toContain('<link rel="canonical" href="/curriculum.html" />');
  });

  it('and got no generated block', () => {
    expect(fs.readFileSync('learn.html', 'utf8')).not.toContain('meta:begin');
  });

  it('the generator skips any page with a hand-written canonical', () => {
    const gen = fs.readFileSync('scripts/build-meta.py', 'utf8');
    expect(gen).toContain('if \'rel="canonical"\' in without_block:');
  });
});
