/* Generates the home page's scrolling trail from assets/data/courses.json.
 *
 *   node scripts/build-trail.mjs          write index.html
 *   node scripts/build-trail.mjs --check  exit 1 if index.html is stale
 *
 * The trail is segments: one per course, each its own <svg> with its own
 * winding path, stops and cards, stacked in one sticky viewport. path-trail.js
 * reads the segments back out of the markup (data-segment, data-span) and maps
 * overall scroll progress across them, so the order, the number of stops and
 * the scroll budget all live here, in one place, instead of in twenty
 * hand-copied blocks.
 *
 * Only the region between the trail:begin and trail:end markers is written.
 * Everything else in index.html, including the intro copy above the trail, is
 * hand-maintained.
 *
 * Numbering: trail stops count across courses (1-20), but every link goes to
 * that course's own unit, from courses.json `first`. A stop's display number is
 * never used to build a path, and a unit's own `n` is never displayed.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const INDEX = path.join(ROOT, 'index.html');
const BEGIN = '<!-- trail:begin (generated by scripts/build-trail.mjs from assets/data/courses.json; do not edit by hand) -->';
const END = '<!-- trail:end -->';

/* The Foundations route, unchanged from the hand-written original. Its ten
   anchor points are where the stops sit before path-trail.js re-places them
   by arc length, so a page without JS still has its stops on the line. */
const ROUTE_1 = {
  d: 'M 72 72 C 150 72 150 150 230 150 S 310 72 390 72 S 500 150 500 210 S 420 290 340 290 S 220 230 160 290 S 160 390 240 390 S 360 450 440 390 S 560 330 560 420 S 480 500 400 500',
  anchors: [[72, 72], [230, 150], [390, 72], [500, 210], [340, 290], [160, 290], [240, 390], [440, 390], [560, 420], [400, 500]],
  label: [[96, 56, ''], [248, 178, ''], [414, 56, ''], [420, 230, 'end'], [358, 268, ''], [90, 268, ''], [258, 418, ''], [458, 372, ''], [480, 448, 'end'], [418, 522, '']],
};

/* Segments, in trail order. `span` is the scroll budget in viewport heights
   for the whole segment; `seam` is the scroll between this segment and the
   next, where the scenery cross-fades. */
export const SEGMENTS = [
  { course: 'foundations', scene: 1, route: ROUTE_1, span: 420, seam: 0 },
];

// The page adds one viewport of track so the last stop is reachable, and the
// sticky layout on phones is shorter, so it gets proportionally less.
const MOBILE_SCALE = 380 / 420;

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function coursesBySlug(doc = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets/data/courses.json'), 'utf8'))) {
  return Object.fromEntries(doc.courses.map((c) => [c.slug, c]));
}

/* A unit's card copy. Foundations keeps it in courses.json; Python for Data's
   blurb is the one its own pages show, from the data course content modules,
   so the two can never disagree. */
function unitsFor(course) {
  let dataContent = null;
  return course.units.map((u) => {
    let blurb = u.blurb;
    if (!blurb && course.slug === 'data') {
      dataContent = dataContent || require('./data-course-content.cjs');
      blurb = dataContent[`unit${u.n}`].blurb;
    }
    for (const field of ['title', 'label', 'hours', 'level', 'first']) {
      if (!u[field]) throw new Error(`courses.json ${course.slug} unit ${u.n} has no ${field}`);
    }
    if (!blurb) throw new Error(`no blurb for ${course.slug} unit ${u.n}`);
    return { ...u, blurb };
  });
}

function segmentSvg(seg, units, offset) {
  const { route } = seg;
  const stops = units.map((u, i) => {
    const [cx, cy] = route.anchors[i];
    const [lx, ly, anchor] = route.label[i];
    return `
                <g class="g-stop" data-stop data-stop-index="${offset + i}">
                  <circle class="path-stop-dot" cx="${cx}" cy="${cy}" r="14" />
                  <text class="path-stop-num" x="${cx}" y="${cy}">${offset + i + 1}</text>
                  <text class="path-stop-label" x="${lx}" y="${ly}"${anchor ? ` text-anchor="${anchor}"` : ''}>${esc(u.label)}</text>
                </g>`;
  }).join('');
  const [hx, hy] = route.anchors[0];
  return `
              <svg class="path-map" data-segment="${seg.scene}" data-course="${seg.course}" data-span="${seg.span}" data-seam="${seg.seam}" viewBox="0 0 640 560" preserveAspectRatio="xMidYMid meet">
                <!-- soft grid -->
                <g class="path-map__grid" opacity="0.7">
                  <path d="M40 40 H600 M40 120 H600 M40 200 H600 M40 280 H600 M40 360 H600 M40 440 H600 M40 520 H600" />
                  <path d="M80 20 V540 M160 20 V540 M240 20 V540 M320 20 V540 M400 20 V540 M480 20 V540 M560 20 V540" />
                </g>

                <!-- base + draw share the same route -->
                <path class="path-map__base" pathLength="1" d="${route.d}" />
                <path class="path-map__draw" pathLength="1" d="${route.d}" />
${stops}

                <!-- traveler head that follows the stroke -->
                <g class="path-head" transform="translate(${hx},${hy})">
                  <circle class="path-head__ring" r="16" />
                  <circle class="path-head__core" r="6" />
                </g>
              </svg>`;
}

function card(u, index, course, seg, first) {
  const button = course.slug === 'foundations' ? `Open Unit ${u.n}` : `Open ${u.title}`;
  return `
                <article class="path-stop-card${first ? ' is-active' : ''}" data-stop-card data-stop-index="${index}" data-segment="${seg.scene}">
                  <div class="path-stop-card__num">${index + 1}</div>
                  <h3>${esc(u.title)}</h3>
                  <p>${esc(u.blurb)}</p>
                  <div class="path-stop-card__meta"><span>${esc(u.hours)}</span><span>${esc(u.level)}</span></div>
                  <a class="btn-path btn-path--primary route" href="${esc(u.first)}">${esc(button)}</a>
                </article>`;
}

export function buildTrail(segments = SEGMENTS, courses = coursesBySlug()) {
  let offset = 0;
  const svgs = [];
  const cards = [];
  let spanTotal = 0;
  segments.forEach((seg, si) => {
    const course = courses[seg.course];
    if (!course) throw new Error(`no course ${seg.course} in courses.json`);
    const units = unitsFor(course);
    if (units.length !== seg.route.anchors.length) {
      throw new Error(`${seg.course} has ${units.length} units but its route has ${seg.route.anchors.length} anchors`);
    }
    svgs.push(segmentSvg(seg, units, offset));
    units.forEach((u, i) => cards.push(card(u, offset + i, course, seg, offset + i === 0)));
    offset += units.length;
    spanTotal += seg.span + (si < segments.length - 1 ? seg.seam : 0);
  });
  const desktop = 100 + spanTotal;
  const mobile = Math.round(100 + spanTotal * MOBILE_SCALE);
  return `${BEGIN}
        <div class="path-journey__track" data-stops="${offset}" style="--trail-length: ${desktop}vh; --trail-length-mobile: ${mobile}vh">
          <div class="path-journey__sticky">
            <div class="path-journey__map" aria-hidden="true">
              <svg class="path-map__defs" width="0" height="0" aria-hidden="true" focusable="false">
                <defs>
                  <linearGradient id="pathGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0%" stop-color="#0284c7" />
                    <stop offset="55%" stop-color="#0ea5e9" />
                    <stop offset="100%" stop-color="#38bdf8" />
                  </linearGradient>
                </defs>
              </svg>${svgs.join('')}
            </div>

            <aside class="path-panel" aria-live="polite">
              <p class="path-panel__kicker">Now on the trail</p>
              <div class="path-panel__progress" aria-hidden="true"><span></span></div>
              <div class="path-panel__stage">${cards.join('')}
              </div>
            </aside>
          </div>
        </div>
        ${END}`;
}

export function renderIndex(html, trail = buildTrail()) {
  const start = html.indexOf(BEGIN);
  const end = html.indexOf(END);
  if (start === -1 || end === -1) throw new Error('index.html has no trail:begin / trail:end markers');
  return html.slice(0, start) + trail + html.slice(end + END.length);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const html = fs.readFileSync(INDEX, 'utf8');
  const next = renderIndex(html);
  if (process.argv.includes('--check')) {
    if (next !== html) {
      console.error('index.html trail is stale: run node scripts/build-trail.mjs');
      process.exit(1);
    }
    console.log('index.html trail is up to date');
  } else {
    fs.writeFileSync(INDEX, next);
    console.log('wrote the trail into index.html');
  }
}
