/* Generates the home page's scrolling trail from assets/data/courses.json.
 *
 *   node scripts/build-trail.mjs          write index.html
 *   node scripts/build-trail.mjs --check  exit 1 if index.html is stale
 *
 * The trail is segments: one per course, each its own <svg> with its own
 * route, stops and cards, stacked in one sticky viewport. path-trail.js reads
 * the segments back out of the markup (data-segment, data-span, data-at) and
 * maps overall scroll progress across them, so the order, the number of stops,
 * the geometry and the scroll budget all live here.
 *
 * Only the region between the trail:begin and trail:end markers is written,
 * plus the versioned URLs of the trail's stylesheet and script (see VERSIONED).
 * Everything else in index.html, including the intro copy above the trail, is
 * hand-maintained.
 *
 * Numbering: map stops count across courses (1-20) and the panel says "Stop 14
 * of 20". Cards say which unit of which course a stop is ("Unit 4 of Python for
 * Data"). Every link goes to that course's own unit, from courses.json `first`;
 * a stop's number is never used to build a path.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const INDEX = path.join(ROOT, 'index.html');
const BEGIN = '<!-- trail:begin (generated by scripts/build-trail.mjs from assets/data/courses.json; do not edit by hand) -->';
const END = '<!-- trail:end -->';

/* ── Geometry ────────────────────────────────────────────────────────────
 *
 * Stops are laid out on a serpentine: rows of 3 and 4 that alternate
 * direction, on an offset (triangular) lattice. In a 4-stop row the stops sit
 * a column apart; a 3-stop row sits half a column in. With the row height at
 * about 0.9 of the column spacing, the stop that ends one row and the stop that
 * starts the next are the same screen distance apart as two stops in a row, so
 * neighbouring stops are evenly spaced on screen by construction, not by
 * arc length along a hand-drawn curve.
 *
 * The route is a centripetal Catmull-Rom spline through the stops, plus one
 * waypoint outside each row end so the turn swings wide instead of folding.
 * The dots and the `d` come from the same points, and each stop records where
 * it falls along the path (data-at) so the drawn line reaches a stop exactly
 * when that stop lights.
 *
 * Every row breathes a little: a seeded wave and a few units of jitter, the
 * same on every build. Rows keep a clear band above them, which is where the
 * active stop's label goes.
 */
export const MAP = {
  width: 560,
  marginX: 70, // column spacing is (width - 2 * marginX) / 3
  top: 84, // room above the top row for a label
  bottom: 54, // room below the bottom row for the head and the horizon
  rowRatio: 0.92, // row height as a fraction of column spacing
  wave: 0.085, // vertical wave within a row, as a fraction of column spacing
  jitter: 4, // units
  turn: 0.3, // how far past the row end a turn swings, as a fraction of spacing
};

export function seeded(seed) {
  let x = seed >>> 0;
  return () => {
    x = (Math.imul(x, 1664525) + 1013904223) >>> 0;
    return x / 4294967296;
  };
}

const round = (n) => Math.round(n * 10) / 10;

export function rowsFor(count) {
  const rows = [];
  for (let left = count, i = 0; left > 0; i++) {
    const size = Math.min(left, i % 2 === 0 ? 3 : 4);
    rows.push(size);
    left -= size;
  }
  return rows;
}

/* Cubic bezier control points for the centripetal Catmull-Rom segment p1->p2. */
function controls(p0, p1, p2, p3) {
  const d = (a, b) => Math.sqrt(Math.hypot(b.x - a.x, b.y - a.y)) || 1e-6;
  const d1 = d(p0, p1);
  const d2 = d(p1, p2);
  const d3 = d(p2, p3);
  const c1 = {
    x: (d1 * d1 * p2.x - d2 * d2 * p0.x + (2 * d1 * d1 + 3 * d1 * d2 + d2 * d2) * p1.x) / (3 * d1 * (d1 + d2)),
    y: (d1 * d1 * p2.y - d2 * d2 * p0.y + (2 * d1 * d1 + 3 * d1 * d2 + d2 * d2) * p1.y) / (3 * d1 * (d1 + d2)),
  };
  const c2 = {
    x: (d3 * d3 * p1.x - d2 * d2 * p3.x + (2 * d3 * d3 + 3 * d3 * d2 + d2 * d2) * p2.x) / (3 * d3 * (d3 + d2)),
    y: (d3 * d3 * p1.y - d2 * d2 * p3.y + (2 * d3 * d3 + 3 * d3 * d2 + d2 * d2) * p2.y) / (3 * d3 * (d3 + d2)),
  };
  return [c1, c2];
}

function cubicLength(a, c1, c2, b, steps = 64) {
  let len = 0;
  let prev = a;
  for (let i = 1; i <= steps; i++) {
    const t = i / steps;
    const u = 1 - t;
    const pt = {
      x: u * u * u * a.x + 3 * u * u * t * c1.x + 3 * u * t * t * c2.x + t * t * t * b.x,
      y: u * u * u * a.y + 3 * u * u * t * c1.y + 3 * u * t * t * c2.y + t * t * t * b.y,
    };
    len += Math.hypot(pt.x - prev.x, pt.y - prev.y);
    prev = pt;
  }
  return len;
}

/* Lay out `rows` (e.g. [3, 4, 3]) as a serpentine and route a line through it.
 *
 *   climb       rows run bottom to top instead of top to bottom
 *   startRight  the first row runs right to left
 *   pin         {x, y} for the first stop, so a segment can start exactly
 *               where the previous one ended
 */
export function serpentine({ rows, seed = 1, climb = false, startRight = false, pin = null }) {
  const m = MAP;
  const spacing = (m.width - 2 * m.marginX) / 3;
  const rowH = spacing * m.rowRatio;
  const height = Math.round(m.top + (rows.length - 1) * rowH + m.bottom);
  const rand = seeded(seed * 2654435761);

  const stops = [];
  const rowOf = [];
  rows.forEach((size, r) => {
    const y0 = m.top + (climb ? rows.length - 1 - r : r) * rowH;
    const phase = rand() * Math.PI * 2;
    const lift = (rand() - 0.5) * 2 * m.jitter;
    const cols = Array.from({ length: size }, (_, j) => m.marginX + (size === 4 ? j : j + 0.5) * spacing);
    const rightward = (r % 2 === 0) !== startRight;
    if (!rightward) cols.reverse();
    cols.forEach((x, j) => {
      stops.push({
        x: round(x + (rand() - 0.5) * 2 * m.jitter),
        y: round(y0 + lift + Math.sin(phase + j * 2.2) * m.wave * spacing),
      });
      rowOf.push(r);
    });
  });
  if (pin) stops[0] = { x: pin.x, y: pin.y };

  // Waypoints: every stop, plus a swing point outside each turn.
  const points = [];
  stops.forEach((s, i) => {
    points.push({ ...s, stop: i });
    const next = stops[i + 1];
    if (next && rowOf[i + 1] !== rowOf[i]) {
      const right = s.x > m.width / 2;
      const edge = right ? Math.max(s.x, next.x) + m.turn * spacing : Math.min(s.x, next.x) - m.turn * spacing;
      points.push({ x: round(Math.min(m.width - 20, Math.max(20, edge))), y: round((s.y + next.y) / 2), stop: null });
    }
  });

  const at = (i) => points[i];
  const ghost = (a, b) => ({ x: 2 * a.x - b.x, y: 2 * a.y - b.y });
  let d = `M ${points[0].x} ${points[0].y}`;
  const lengths = [0];
  for (let i = 0; i < points.length - 1; i++) {
    const p0 = i === 0 ? ghost(at(0), at(1)) : at(i - 1);
    const p3 = i + 2 >= points.length ? ghost(at(i + 1), at(i)) : at(i + 2);
    const [c1, c2] = controls(p0, at(i), at(i + 1), p3);
    d += ` C ${round(c1.x)} ${round(c1.y)} ${round(c2.x)} ${round(c2.y)} ${at(i + 1).x} ${at(i + 1).y}`;
    lengths.push(lengths[i] + cubicLength(at(i), c1, c2, at(i + 1)));
  }
  const total = lengths[lengths.length - 1];
  const stopAt = [];
  points.forEach((p, i) => {
    if (p.stop !== null) stopAt[p.stop] = Math.round((lengths[i] / total) * 10000) / 10000;
  });

  return { width: m.width, height, spacing, rowH, stops, points, d, at: stopAt, length: total };
}

/* Segments, in trail order. `span` is the scroll budget in viewport heights
   for the whole segment; `seam` is the scroll after it, where the maps and the
   scenery cross-fade into the next segment.

   Both courses get 36vh a stop, and the 60vh seam sits in the middle of the
   track (46% to 54%), so the arrival at the second course is the midpoint of
   the scroll rather than an event squeezed in after it.

   Python for Data climbs back up from where Foundations ends (its first stop is
   pinned to Foundations' last), with its rows the other way round, so the two
   maps are different shapes and the gateway sits where the finish was. */
export const SEGMENTS = [
  { course: 'foundations', scene: 1, line: 'marked', rows: [3, 4, 3], seed: 11, climb: false, startRight: false, span: 360, seam: 60 },
  { course: 'data', scene: 2, line: 'flat', rows: [3, 3, 4], seed: 29, climb: true, startRight: true, pinToPrevious: true, span: 360, seam: 0 },
];

// The page adds one viewport of track so the last stop is reachable, and the
// sticky layout on phones is shorter, so it gets proportionally less.
const MOBILE_SCALE = 380 / 420;

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function coursesBySlug(doc = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets/data/courses.json'), 'utf8'))) {
  return Object.fromEntries(doc.courses.map((c) => [c.slug, c]));
}

/* A unit's card copy. Foundations keeps it in courses.json; Python for Data's
   blurb is the one its own pages show, from the data course content modules,
   so the two can never disagree. */
function unitsFor(course) {
  let dataContent = null;
  return course.units.map((u) => {
    let blurb = u.blurb;
    if (!blurb && course.slug === 'data') {
      dataContent = dataContent || require('./data-course-content.cjs');
      blurb = dataContent[`unit${u.n}`].blurb;
    }
    for (const field of ['title', 'label', 'hours', 'level', 'first']) {
      if (!u[field]) throw new Error(`courses.json ${course.slug} unit ${u.n} has no ${field}`);
    }
    if (!blurb) throw new Error(`no blurb for ${course.slug} unit ${u.n}`);
    return { ...u, blurb };
  });
}

/* ── Scenery ─────────────────────────────────────────────────────────────
   Sparse terraces occupy the spaces between route rows. All scenery shares
   the route's viewBox, so resizing never separates landmarks from the path.
   Palette tokens live in home-path.css; no runtime work or image assets. */
function nearRoute(geo, x, y, clearance) {
  return geo.points.some((p, i) => {
    const q = geo.points[i + 1];
    if (!q) return Math.hypot(p.x - x, p.y - y) < clearance;
    for (let t = 0; t <= 1; t += 0.1) {
      if (Math.hypot(p.x + (q.x - p.x) * t - x, p.y + (q.y - p.y) * t - y) < clearance) return true;
    }
    return false;
  });
}

function spaceLandmark(kind) {
  if (kind === 0) return '<circle r="17" /><circle cx="-6" cy="-4" r="4" /><circle cx="7" cy="6" r="3" /><path d="M2 -12 a9 9 0 0 1 9 9" />';
  if (kind === 1) return '<circle r="12" /><ellipse rx="25" ry="6" transform="rotate(-25)" />';
  return '<path d="M-15 7 Q-7 -11 8 -15 Q14 -1 3 11 Z M-9 1 L-18 0 L-21 11 L-11 9 M4 7 L7 18 L-4 21 L-4 12 M-13 14 L-19 20" /><circle cx="3" cy="-5" r="3" />';
}

function landmark(kind) {
  if (kind === 0) return '<path d="M-14 6 L-2 -12 L12 6 Z M-5 6 L9 -6 L20 6 M-6 -6 L-2 -2 L2 -6" />';
  if (kind === 1) return '<path d="M-16 9 L-3 -14 L10 9 Z M-7 -6 L-3 -2 L1 -6 M5 9 L15 -6 L25 9" />';
  return '<path d="M-12 13 V-10 M-21 2 L-12 -13 L-3 2 Z M2 9 L13 -9 L24 9 Z" />';
}

export function scenery(seg, geo) {
  const { width: w, height: h } = geo;
  const clusters = [];
  // Search in the lower half of each row gap, below the next label band.
  for (let row = 0; row < seg.rows.length - 1; row++) {
    const y = round(MAP.top + (row + 0.48) * geo.rowH);
    const candidates = row % 2 ? [w * 0.68, w * 0.32] : [w * 0.3, w * 0.7];
    candidates.forEach((x, i) => {
      if (nearRoute(geo, x, y, 50)) return;
      if (seg.scene === 2) {
        clusters.push(`<g class="trail-landscape__cluster trail-landscape__space" transform="translate(${round(x)} ${y})"><g class="trail-landscape__landmark">${spaceLandmark((row + i) % 3)}</g><path class="trail-landscape__detail" d="M-37 -15 h6 m-3 -3 v6 M29 22 h6 m-3 -3 v6" /></g>`);
        return;
      }
      clusters.push(`<g class="trail-landscape__cluster" transform="translate(${round(x)} ${y})">
                  <path class="trail-landscape__shelf" d="M-44 10 Q-50 -5 -31 -12 L-9 -19 Q6 -24 25 -12 L44 0 Q53 14 32 21 L4 27 Q-12 30 -29 21 Z" />
                  <path class="trail-landscape__terrace" d="M-44 4 Q-50 -11 -31 -18 L-9 -25 Q6 -30 25 -18 L44 -6 Q53 8 32 15 L4 21 Q-12 24 -29 15 Z" />
                  <g class="trail-landscape__landmark">${landmark((row + i + (seg.scene - 1)) % 3)}</g>
                  <path class="trail-landscape__detail" d="M-31 34 h12 m4 0 h3 M31 -28 h7 m-3.5 -3.5 v7" />
                </g>`);
    });
  }
  let stars = '';
  if (seg.scene === 2) {
    const rand = seeded(seg.seed);
    for (let i = 0; i < 36; i++) {
      const x = round(20 + rand() * (w - 40));
      const y = round(20 + rand() * (h - 40));
      if (!nearRoute(geo, x, y, 32)) stars += `<circle cx="${x}" cy="${y}" r="${i % 4 === 0 ? 1.5 : 0.8}" />`;
    }
  }
  return `
                <g class="trail-landscape" aria-hidden="true" focusable="false">
                  <path class="trail-landscape__edge" d="M18 36 V18 H40 M${w - 40} 18 H${w - 18} V36 M18 ${h - 36} V${h - 18} H40 M${w - 40} ${h - 18} H${w - 18} V${h - 36}" />
                  <g class="trail-landscape__stars">${stars}</g>${clusters.join('')}
                  <g class="trail-landscape__detail" transform="translate(${w / 2} ${h - 20})"><path d="M-22 0 h12 M10 0 h12" /><circle r="2" /></g>
                </g>`;
}

function callout(extra, label, x, y) {
  // A first guess at the label's size, for a page without scripting;
  // path-trail.js measures the real text and places it.
  const w = Math.round(label.length * 8.4 + 26);
  return `
                <g class="trail-callout${extra}" aria-hidden="true">
                  <g class="trail-callout__body">
                    <line class="trail-callout__leader" x1="${x}" y1="${y - 20}" x2="${x}" y2="${y - 30}" />
                    <rect class="trail-callout__pill" x="${x - w / 2}" y="${y - 60}" width="${w}" height="30" rx="15" />
                    <text class="trail-callout__text" x="${x}" y="${y - 45}">${esc(label)}</text>
                  </g>
                </g>`;
}

/* The route. A `marked` line is a cased trail: a soft casing, the unwalked
   line, the walked line in a solid color, and a row of trail markers that only
   show on the walked part (masked by the same scroll progress). A `flat` line
   is one solid colour over a dotted unwalked line, with flat colors. */
function route(seg, geo) {
  if (seg.line === 'marked') {
    return `
                <path class="path-map__casing" d="${geo.d}" />
                <path class="path-map__base" pathLength="1" d="${geo.d}" />
                <path class="path-map__draw" pathLength="1" d="${geo.d}" />
                <mask id="trailReveal${seg.scene}" maskUnits="userSpaceOnUse" x="0" y="0" width="${geo.width}" height="${geo.height}">
                  <path class="path-map__reveal" pathLength="1" d="${geo.d}" />
                </mask>
                <path class="path-map__markers" d="${geo.d}" mask="url(#trailReveal${seg.scene})" />`;
  }
  return `
                <path class="path-map__base" pathLength="1" d="${geo.d}" />
                <path class="path-map__draw path-map__draw--flat" pathLength="1" d="${geo.d}" />`;
}

/* A segment's first stop, after the first segment, is a gateway, and every
   segment's last stop is a finish: the change of course is marked on the map,
   not just in the colours. */
function segmentSvg(seg, geo, units, offset, si) {
  const stops = units.map((u, i) => {
    const { x, y } = geo.stops[i];
    const end = i === units.length - 1;
    const gate = i === 0 && si > 0;
    const cls = `trail-stop${end ? ' trail-stop--end' : ''}${gate ? ' trail-stop--start' : ''}`;
    // The flag sits outside the scaled mark, so growing the active dot never
    // moves its centre.
    const flag = end
      ? `
                  <path class="trail-stop__flag" d="M10 -10 V-36 L29 -29.5 L10 -23" />`
      : '';
    const gateRing = gate
      ? `
                    <circle class="trail-stop__gate" r="21" />`
      : '';
    return `
                <g class="${cls}" data-stop data-stop-index="${offset + i}" data-at="${geo.at[i]}" data-label="${esc(u.label)}" transform="translate(${x} ${y})">${flag}
                  <g class="trail-stop__mark">
                    <circle class="trail-stop__halo" r="23" />${gateRing}
                    <circle class="trail-stop__dot" r="13" />
                    <text class="trail-stop__num">${offset + i + 1}</text>
                  </g>
                </g>`;
  }).join('');
  const first = geo.stops[0];
  return `
              <svg class="path-map" data-segment="${seg.scene}" data-course="${seg.course}" data-span="${seg.span}" data-seam="${seg.seam}" data-stops="${units.length}" viewBox="0 0 ${geo.width} ${geo.height}" preserveAspectRatio="xMidYMid meet">${scenery(seg, geo)}

${route(seg, geo)}

                <g class="path-head" transform="translate(${first.x} ${first.y})">
                  <circle class="path-head__ring" r="12" />
                  <circle class="path-head__core" r="5" />
                </g>
${stops}
${callout('', units[0].label, first.x, first.y)}
${callout(' trail-callout--peek', '', first.x, first.y)}
              </svg>`;
}

function card(u, index, course, seg, first) {
  return `
                <article class="path-stop-card${first ? ' is-active' : ''}" data-stop-card data-stop-index="${index}" data-segment="${seg.scene}">
                  <p class="path-stop-card__where"><span class="path-stop-card__unit">Unit ${u.n}</span> <span>${esc(course.title)}</span></p>
                  <h3>${esc(u.title)}</h3>
                  <p class="path-stop-card__blurb">${esc(u.blurb)}</p>
                  <div class="path-stop-card__meta"><span>${esc(u.hours)}</span><span>${esc(u.level)}</span></div>
                  <a class="btn-path btn-path--primary route" href="${esc(u.first)}">Open ${esc(u.title)}</a>
                </article>`;
}

export function geometryFor(segments = SEGMENTS) {
  const out = [];
  segments.forEach((seg, i) => {
    const prev = out[i - 1];
    out.push(serpentine({
      rows: seg.rows,
      seed: seg.seed,
      climb: seg.climb,
      startRight: seg.startRight,
      pin: seg.pinToPrevious && prev ? prev.stops[prev.stops.length - 1] : null,
    }));
  });
  return out;
}

export function buildTrail(segments = SEGMENTS, courses = coursesBySlug()) {
  const geos = geometryFor(segments);
  if (new Set(geos.map((g) => g.height)).size !== 1) {
    throw new Error('every segment must have the same number of rows, so the maps share one frame');
  }

  let offset = 0;
  const svgs = [];
  const cards = [];
  const markers = [];
  const jumps = [];
  const spanTotal = segments.reduce((sum, seg, si) => sum + seg.span + (si < segments.length - 1 ? seg.seam : 0), 0);
  let at = 0;
  segments.forEach((seg, si) => {
    const course = courses[seg.course];
    if (!course) throw new Error(`no course ${seg.course} in courses.json`);
    const units = unitsFor(course);
    const planned = seg.rows.reduce((a, b) => a + b, 0);
    if (units.length !== planned) {
      throw new Error(`${seg.course} has ${units.length} units but its rows ${JSON.stringify(seg.rows)} hold ${planned}`);
    }
    svgs.push(segmentSvg(seg, geos[si], units, offset, si));
    units.forEach((u, i) => cards.push(card(u, offset + i, course, seg, offset + i === 0)));
    if (segments.length > 1) {
      // Where this segment starts on the scroll track. The course switcher
      // lands here with scripting, and an in-page link is the fallback.
      markers.push(`
          <span class="path-journey__marker" id="trail-${seg.course}" style="--at: ${at}vh; --at-mobile: ${round(at * MOBILE_SCALE)}vh"></span>`);
      jumps.push(`<a class="path-courses__link" href="#trail-${seg.course}" data-trail-jump="${seg.scene}" data-stop-index="${offset}"${si === 0 ? ' aria-current="true"' : ''}>${esc(course.title)}</a>`);
    }
    offset += units.length;
    at += seg.span + (si < segments.length - 1 ? seg.seam : 0);
  });

  const desktop = 100 + spanTotal;
  const mobile = Math.round(100 + spanTotal * MOBILE_SCALE);
  const ratio = Math.round((geos[0].width / geos[0].height) * 1000) / 1000;
  const nav = jumps.length
    ? `
              <nav class="path-courses" aria-label="Courses on the trail">
                ${jumps.join('\n                ')}
              </nav>`
    : '';
  return `${BEGIN}
        <div class="path-journey__track" data-stops="${offset}" style="--trail-length: ${desktop}vh; --trail-length-mobile: ${mobile}vh">${markers.join('')}
          <div class="path-journey__sticky">
            <div class="path-journey__map" aria-hidden="true" style="--map-ratio: ${ratio}">
${svgs.join('')}${segments.length > 1 ? `
              <p class="path-journey__gate"><span>Next adventure</span> ${esc(courses[segments[1].course].title)}</p>` : ''}
            </div>

            <aside class="path-panel" aria-label="Units on the trail">${nav}
              <div class="path-panel__progress" aria-hidden="true">
                <p class="path-panel__count">Stop <span data-trail-count>1</span> of ${offset}</p>
                <div class="path-panel__bar"><span></span></div>
              </div>
              <div class="path-panel__stage">${cards.join('')}
              </div>
            </aside>
          </div>
          <dialog class="trail-transition" aria-labelledby="trail-transition-title" aria-describedby="trail-transition-description">
            <p class="trail-transition__eyebrow">Next adventure · Stops 11–20</p>
            <h2 id="trail-transition-title">Ready to explore Python for Data?</h2>
            <p id="trail-transition-description">Leave the mountain for a journey through space. Explore data, discover patterns, and build on your Python skills.</p>
            <div class="trail-transition__actions">
              <button type="button" class="btn-path btn-path--primary" data-trail-continue>Yes, explore space</button>
              <button type="button" class="btn-path btn-path--ghost" data-trail-stay autofocus>Stay on Foundations</button>
            </div>
          </dialog>
        </div>
        ${END}`;
}

/* The trail's stylesheet and script are versioned by content.

   index.html is served must-revalidate, but /assets/(css|js)/* is cached for an
   hour and then served stale for up to a day while it revalidates. On
   unversioned URLs a returning visitor got the new trail markup with the old
   CSS and JS: both jump links as one underlined string, the progress bar
   drawn through them, all 20 stops piled onto the first line. The markup and
   these two files are only correct together, so their URLs change whenever
   either file does, and --check fails if index.html still points at old ones. */
export const VERSIONED = ['assets/css/home-path.css', 'assets/js/path-trail.js', 'assets/js/summit-3d.js', 'assets/img/data-moon.svg'];

export function assetVersion(rel) {
  return createHash('sha256').update(fs.readFileSync(path.join(ROOT, rel))).digest('hex').slice(0, 10);
}

export function renderIndex(html, trail = buildTrail(), versions = Object.fromEntries(VERSIONED.map((rel) => [rel, assetVersion(rel)]))) {
  const start = html.indexOf(BEGIN);
  const end = html.indexOf(END);
  if (start === -1 || end === -1) throw new Error('index.html has no trail:begin / trail:end markers');
  let out = html.slice(0, start) + trail + html.slice(end + END.length);
  for (const [rel, v] of Object.entries(versions)) {
    const url = '/' + rel;
    const re = new RegExp(`(["'])${url.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}(?:\\?v=[0-9a-f]+)?\\1`, 'g');
    if (!re.test(out)) throw new Error(`index.html does not reference ${url}`);
    out = out.replace(re, `$1${url}?v=${v}$1`);
  }
  return out;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const html = fs.readFileSync(INDEX, 'utf8');
  const next = renderIndex(html);
  if (process.argv.includes('--check')) {
    if (next !== html) {
      console.error('index.html trail is stale: run node scripts/build-trail.mjs');
      process.exit(1);
    }
    console.log('index.html trail is up to date');
  } else {
    fs.writeFileSync(INDEX, next);
    console.log('wrote the trail into index.html');
  }
}
