#!/usr/bin/env python3
"""Apply one <noscript> policy across the site.

THE POLICY, decided here rather than left implied:

  A page whose PRIMARY FUNCTION requires JavaScript says so, in its own words,
  where the content would have been. A page that is readable without JavaScript
  says nothing, because a banner announcing a dependency that does not affect
  you is noise.

That splits the site three ways.

  APP PAGES are entirely non-functional without JS -- the teacher dashboard,
  the account and settings pages, the certificate, progress, the sandbox, and
  both auth forms. Every one of them renders an empty shell and waits for a
  script that will never run. They get a notice naming what specifically will
  not work, not a generic "enable JavaScript".

  LESSON PAGES are the interesting case and the reason this is a policy rather
  than a find-and-replace. The lesson TEXT is static HTML and reads perfectly
  well with scripting off: someone on a locked-down school machine can still
  learn from it. What does not work is the runnable code, the checks and the
  saved progress. So they get a softer notice that says exactly that, and does
  not tell someone the page is broken when most of it is not.

  CONTENT PAGES -- the homepage, curriculum, courses, the two course indexes,
  privacy, terms -- are fully readable and get nothing.

Before this, two pages out of 198 had a <noscript> and there was no stated
reason why those two.

    python3 scripts/build-noscript.py            # report
    python3 scripts/build-noscript.py --apply    # write
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APPLY = "--apply" in sys.argv

BEGIN = "<!-- noscript:begin (generated by scripts/build-noscript.py) -->"
END = "<!-- noscript:end -->"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

# What each app page actually loses. Naming the specific thing beats "this page
# requires JavaScript", which tells someone nothing they cannot already see.
APP = {
    "classroom.html": "The class dashboard needs JavaScript: your students' progress is read "
                      "from the database and drawn in your browser.",
    "account.html": "Your account details need JavaScript to load.",
    "settings.html": "Settings need JavaScript: your preferences are read and saved in your browser.",
    "certificate.html": "The certificate needs JavaScript, because it is generated in your browser "
                        "from your progress.",
    "progress.html": "Your progress needs JavaScript to load.",
    "sandbox.html": "The sandbox needs JavaScript: it runs Python in your browser.",
    "login.html": "Signing in needs JavaScript.",
    "signup.html": "Creating an account needs JavaScript.",
    "admin.html": "The admin dashboard needs JavaScript.",
}

LESSON = ("This lesson's text is readable without JavaScript, but the code editors, "
          "the checks and your saved progress will not work until it is switched on.")

SKIP_DIRS = {".git", "node_modules", "lesson-format-kit", "REVIEW", "docs"}


def is_lesson(path: Path) -> bool:
    parts = path.relative_to(ROOT).parts
    return len(parts) > 1 and parts[0] in {"units", "data"}


def notice(path: Path) -> str | None:
    if path.name in APP:
        return APP[path.name]
    if is_lesson(path):
        return LESSON
    return None


def block(message: str) -> str:
    return (
        f'{BEGIN}\n      <noscript>\n'
        f'        <p class="noscript-notice">{message}</p>\n'
        f'      </noscript>\n      {END}'
    )


def main() -> int:
    added = updated = unchanged = skipped = 0
    for path in sorted(ROOT.rglob("*.html")):
        if any(p in SKIP_DIRS for p in path.parts):
            continue

        message = notice(path)
        src = path.read_text(encoding="utf-8")

        if message is None:
            # A content page. If a previous run put a block here, take it back
            # out -- the policy is that these say nothing.
            if BLOCK_RE.search(src):
                if APPLY:
                    path.write_text(BLOCK_RE.sub("", src), encoding="utf-8")
                updated += 1
            else:
                skipped += 1
            continue

        # Hand-written <noscript> outside our block stays. quiz.html and
        # unit-test.html said it well before this script existed and their
        # wording is better than a generated line.
        if "<noscript" in BLOCK_RE.sub("", src):
            skipped += 1
            continue

        new_block = block(message)
        if BLOCK_RE.search(src):
            new = BLOCK_RE.sub(lambda _: new_block, src)
            if new == src:
                unchanged += 1
                continue
            updated += 1
        else:
            m = re.search(r"<main\b[^>]*>", src, re.I)
            if not m:
                skipped += 1
                continue
            # First thing inside <main>, so it lands where the content would
            # have been rather than under a header the reader has already
            # passed.
            new = src[: m.end()] + "\n      " + new_block + src[m.end():]
            added += 1

        if APPLY:
            path.write_text(new, encoding="utf-8")

    print(f"added {added}, updated {updated}, unchanged {unchanged}, skipped {skipped}")
    if not APPLY and (added or updated):
        print("\nNothing was written. Re-run with --apply.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
