#!/usr/bin/env python3
"""Generate og:/twitter:/canonical tags for every page, from the page itself.

WHY THIS EXISTS. Only /index.html had Open Graph tags and a canonical URL.
Every other page -- 197 of them, including the ~190 lesson pages a teacher
actually shares -- had none, so a lesson link posted into a school's Slack or
into Google Classroom previewed as a bare URL. That is the moment the product
is being recommended by one teacher to another, and it looked broken.

GENERATED, NOT HAND-MAINTAINED, which is the only reason this is worth doing at
all. 198 pages of hand-written meta tags would be wrong within a month: the
titles drift, someone renames a lesson, and nobody notices because a preview
card is invisible from inside the site.

WHERE THE VALUES COME FROM. The page's own <title> and <meta name="description">,
both of which already exist everywhere and are already checked by
scripts/check_meta.py. So this adds no new content to maintain -- it projects
what is already there into the tags a scraper reads. A page whose title changes
gets a corrected card the next time this runs.

IDEMPOTENT. It rewrites its own block, marked by a comment, and leaves anything
hand-written alone -- /index.html's tags predate this and are richer than what
would be generated, so they are left exactly as they are.

    python3 scripts/build-meta.py            # report what would change
    python3 scripts/build-meta.py --apply    # write
"""
from __future__ import annotations
import html as htmllib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://mypypath.com"
APPLY = "--apply" in sys.argv

SKIP_DIRS = {".git", "node_modules", "lesson-format-kit", "REVIEW", "docs"}
# Pages that must never advertise themselves to a crawler or a card scraper.
SKIP_FILES = {"404.html", "admin.html", "sandbox-export.html"}

BEGIN = "<!-- meta:begin (generated by scripts/build-meta.py — do not edit by hand) -->"
END = "<!-- meta:end -->"

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S | re.I)
DESC_RE = re.compile(
    r'<meta\s+name=["\']description["\']\s+content=["\'](.*?)["\']', re.S | re.I
)
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
HEAD_END_RE = re.compile(r"</head>", re.I)


def url_for(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if rel == "index.html":
        return SITE + "/"
    return f"{SITE}/{rel}"


def text_of(match: re.Match | None) -> str:
    if not match:
        return ""
    # Collapse the whitespace a multi-line title or description carries, then
    # unescape so we are working with real characters before re-escaping for
    # the attribute.
    return htmllib.unescape(re.sub(r"\s+", " ", match.group(1)).strip())


def attr(value: str) -> str:
    return htmllib.escape(value, quote=True)


def block_for(path: Path, source: str) -> str | None:
    title = text_of(TITLE_RE.search(source))
    desc = text_of(DESC_RE.search(source))
    if not title:
        return None

    url = url_for(path)
    # A lesson page's <title> carries the site name; a card that repeats it in
    # the title AND the site_name line reads as a stutter, so it is trimmed for
    # the card only and left alone in the tab.
    card_title = re.sub(r"\s*[|•·—–-]\s*PyPath\s*$", "", title).strip() or title

    lines = [
        BEGIN,
        '<meta property="og:type" content="article" />'
        if "/units/" in url or "/data/" in url
        else '<meta property="og:type" content="website" />',
        '<meta property="og:site_name" content="PyPath" />',
        f'<meta property="og:title" content="{attr(card_title)}" />',
    ]
    if desc:
        lines.append(f'<meta property="og:description" content="{attr(desc)}" />')
    lines += [
        f'<meta property="og:url" content="{attr(url)}" />',
        f'<meta property="og:image" content="{SITE}/assets/img/og-card.png" />',
        '<meta property="og:image:width" content="512" />',
        '<meta property="og:image:height" content="512" />',
        '<meta name="twitter:card" content="summary" />',
        f'<meta name="twitter:title" content="{attr(card_title)}" />',
    ]
    if desc:
        lines.append(f'<meta name="twitter:description" content="{attr(desc)}" />')
    lines.append(f'<link rel="canonical" href="{attr(url)}" />')
    lines.append(END)
    return "\n    ".join(lines)


def main() -> int:
    pages = []
    for p in sorted(ROOT.rglob("*.html")):
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        if p.name in SKIP_FILES:
            continue
        pages.append(p)

    added = updated = unchanged = skipped = 0
    for p in pages:
        src = p.read_text(encoding="utf-8")

        # Already has hand-written Open Graph tags outside our block: leave it
        # alone. index.html's are richer than anything generated here.
        without_block = BLOCK_RE.sub("", src)
        if 'property="og:' in without_block:
            skipped += 1
            continue

        # A hand-written canonical is a DELIBERATE statement, and often points
        # somewhere else on purpose. learn.html is a redirect stub whose
        # canonical is /curriculum.html; adding a second one pointing at itself
        # told a crawler two contradictory things about the same page and undid
        # the very thing that canonical was there to do.
        if 'rel="canonical"' in without_block:
            skipped += 1
            continue

        block = block_for(p, src)
        if not block:
            skipped += 1
            continue

        if BLOCK_RE.search(src):
            new = BLOCK_RE.sub(lambda _: block, src)
            if new == src:
                unchanged += 1
                continue
            updated += 1
        else:
            m = HEAD_END_RE.search(src)
            if not m:
                skipped += 1
                continue
            new = src[: m.start()] + "    " + block + "\n  " + src[m.start():]
            added += 1

        if APPLY:
            p.write_text(new, encoding="utf-8")

    print(f"{len(pages)} page(s) considered")
    print(f"  added     {added}")
    print(f"  updated   {updated}")
    print(f"  unchanged {unchanged}")
    print(f"  skipped   {skipped}  (hand-written tags, or no <title>)")
    if not APPLY and (added or updated):
        print("\nNothing was written. Re-run with --apply.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
