#!/usr/bin/env python3
"""Regenerate assets/js/curriculum.js — the unit -> ordered lesson map.

Lesson order is curriculum order, not filename order, so it is read from the
links on each unit overview page rather than from the directory listing.
Run this after adding, removing, or reordering a lesson; CI checks it is current.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "js" / "curriculum.js"
TOTAL_UNITS = 10


def lessons_for(unit: int) -> list[str]:
    overview = ROOT / "units" / f"unit-{unit}.html"
    html = overview.read_text(encoding="utf-8")
    seen, ordered = set(), []
    for href in re.findall(rf'href="(/units/unit-{unit}/[a-z0-9-]+\.html)"', html):
        if href not in seen:
            seen.add(href)
            ordered.append(href)
    on_disk = {
        f"/units/unit-{unit}/{p.name}"
        for p in (ROOT / "units" / f"unit-{unit}").glob("*.html")
    }
    missing = sorted(on_disk - seen)
    if missing:
        raise SystemExit(
            f"unit-{unit}: {len(missing)} lesson(s) exist on disk but are not "
            f"linked from unit-{unit}.html, so their order is unknown: {missing}"
        )
    return ordered


def main() -> None:
    units = {u: lessons_for(u) for u in range(1, TOTAL_UNITS + 1)}
    lines = [
        "/* PyPath — generated by scripts/generate_curriculum.py. Do not edit by hand.",
        "   Maps each unit to its lessons in curriculum order. Lesson progress and the",
        "   unit lock both need to know a unit's full lesson list without loading it. */",
        "(function () {",
        "  'use strict';",
        "",
        "  var UNITS = {",
    ]
    for u in range(1, TOTAL_UNITS + 1):
        entries = ",\n".join(f"      '{p}'" for p in units[u])
        lines.append(f"    {u}: [\n{entries}\n    ]" + ("," if u < TOTAL_UNITS else ""))
    lines += [
        "  };",
        "",
        "  function unitOf(pathname) {",
        "    var m = /^\\/units\\/unit-(\\d+)(?:\\/|\\.html$)/.exec(String(pathname || ''));",
        "    return m ? Number(m[1]) : null;",
        "  }",
        "",
        "  window.PyPathCurriculum = {",
        "    TOTAL_UNITS: " + str(TOTAL_UNITS) + ",",
        "    UNITS: UNITS,",
        "    unitOf: unitOf,",
        "    lessonsIn: function (u) { return UNITS[u] ? UNITS[u].slice() : []; }",
        "  };",
        "})();",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    total = sum(len(v) for v in units.values())
    print(f"Wrote {OUT.relative_to(ROOT)} — {TOTAL_UNITS} units, {total} lessons")


if __name__ == "__main__":
    main()
