/* The skill taxonomy, by hand. scripts/build-skills.mjs turns this into
 * assets/data/skills.json; scripts/validate-skills.mjs checks the result.
 *
 * Small on purpose. Fifty skills over 159 lessons is roughly three lessons a
 * skill, which is the most an estimator can separate with the data a class
 * produces. Four hundred fine-grained concepts would each see a handful of
 * attempts and every estimate would be the prior.
 *
 * A skill is { id, name, course, description, prerequisites, keywords }.
 * `keywords` exist only to tag end-of-unit test questions, which -- unlike
 * lesson quiz questions and exercises -- are not attached to a lesson. They
 * are matched against a question's prompt, code, choices and explanation,
 * restricted to the skills of that question's own unit.
 */

const S = (id, name, course, prerequisites, description, keywords = []) =>
  ({ id, name, course, prerequisites, description, keywords });

export const SKILLS = [
  // ------------------------------------------------------------ Foundations
  S('py.running-code', 'Running Python programs', 'foundations', [],
    'What Python is, running a script, print and the shape of a first program.',
    ['print(', 'interpreter', 'script', 'ide', 'install', 'terminal', 'run python', '.py file', 'hello']),
  S('py.syntax', 'Syntax, indentation and comments', 'foundations', ['py.running-code'],
    'Indentation as structure, statements, comments and reading syntax errors.',
    ['indent', 'comment', '#', 'syntaxerror', 'colon', 'whitespace', 'case-sensitive', 'case sensitive']),
  S('py.variables-types', 'Variables and types', 'foundations', ['py.syntax'],
    'Assignment, names, and the core types int, float, str and bool.',
    ['variable', 'type(', 'int', 'float', 'str', 'bool', 'assign', 'name']),
  S('py.input-conversion', 'Input and type conversion', 'foundations', ['py.variables-types'],
    'input(), converting between types, f-strings and formatted output.',
    ['input(', 'int(', 'float(', 'str(', 'convert', 'f"', "f'", 'f-string', 'format', 'valueerror']),
  S('py.arithmetic', 'Arithmetic and expressions', 'foundations', ['py.variables-types'],
    'Operators, precedence, integer and float division, modulo and powers.',
    ['//', '%', '**', 'divide', 'division', 'remainder', 'modulo', 'precedence', 'operator', 'round(']),
  S('py.booleans', 'Comparisons and boolean logic', 'foundations', ['py.variables-types'],
    'Comparison operators, and/or/not, truthiness and short-circuiting.',
    [' and ', ' or ', 'not ', '==', '!=', '>=', '<=', 'true', 'false', 'truthy', 'falsy', 'boolean', 'short-circuit']),
  S('py.conditionals', 'Conditionals', 'foundations', ['py.booleans'],
    'if, elif and else, nested conditions and choosing a branch.',
    ['if ', 'elif', 'else', 'branch', 'condition', 'nested']),
  S('py.while-loops', 'While loops', 'foundations', ['py.conditionals'],
    'Repeating while a condition holds, counters, and infinite loops.',
    ['while', 'infinite', 'counter', 'repeat', 'loop']),
  S('py.for-loops', 'For loops and range', 'foundations', ['py.conditionals'],
    'Iterating over sequences and range(), accumulating results.',
    ['for ', 'range(', 'iterate', 'accumulat', 'enumerate(', 'loop']),
  S('py.loop-control', 'Loop control', 'foundations', ['py.for-loops', 'py.while-loops'],
    'break, continue, else on loops, and combining loops with conditions.',
    ['break', 'continue', 'pass', 'loop else', 'early exit']),
  S('py.functions', 'Defining and calling functions', 'foundations', ['py.for-loops'],
    'def, calling, why functions exist, and splitting a program into pieces.',
    ['def ', 'function', 'call', 'define', 'none']),
  S('py.parameters-return', 'Parameters, arguments and return', 'foundations', ['py.functions'],
    'Positional and keyword arguments, defaults, and returning values.',
    ['return', 'parameter', 'argument', 'default', 'keyword argument', '*args', '**kwargs', 'returns none']),
  S('py.scope', 'Scope and helper functions', 'foundations', ['py.parameters-return'],
    'Local and global scope, lifetime, nested and helper functions.',
    ['scope', 'global', 'local', 'nonlocal', 'nested function', 'helper', 'unboundlocalerror', 'lifetime']),
  S('py.documentation', 'Documenting code', 'foundations', ['py.functions'],
    'Docstrings, useful comments, and documentation a reader can follow.',
    ['docstring', '"""', 'help(', '__doc__', 'documentation', 'readme']),
  S('py.lambdas', 'Lambda functions', 'foundations', ['py.parameters-return'],
    'Anonymous functions, and using them with sorted, map and filter.',
    ['lambda', 'map(', 'filter(', 'key=']),
  S('py.lists', 'Lists', 'foundations', ['py.for-loops'],
    'Creating lists, list methods, and when a list is the right structure.',
    ['list', 'append', '.pop(', '.insert(', '.remove(', '.count(', '.sort(', 'sorted(', 'len(', '[]']),
  S('py.indexing-slicing', 'Indexing, slicing and nested lists', 'foundations', ['py.lists'],
    'Indexes, negative indexes, slices, and lists of lists.',
    ['index', 'slice', '[-1]', '[0]', ':]', '[1:', 'indexerror', 'nested list', '2d', 'grid', 'row']),
  S('py.tuples-sets', 'Tuples and sets', 'foundations', ['py.lists'],
    'Immutable tuples, unpacking, and sets for uniqueness and membership.',
    ['tuple', 'set(', 'set', 'unpack', 'immutable', 'union', 'intersection', 'unique', 'duplicate']),
  S('py.dictionaries', 'Dictionaries', 'foundations', ['py.lists'],
    'Key-value pairs, .get, iterating over items, and dictionary methods.',
    ['dict', 'key', '.get(', '.items(', '.keys(', '.values(', 'keyerror', '{']),
  S('py.mutability', 'Mutability, copying and choosing a structure', 'foundations', ['py.dictionaries', 'py.tuples-sets'],
    'Aliasing, shallow and deep copies, == versus is, and picking a structure.',
    ['copy', 'alias', 'mutable', ' is ', 'deepcopy', 'same object', 'choose', 'choosing', 'identity']),
  S('py.modules', 'Modules and imports', 'foundations', ['py.functions'],
    'import forms, the standard library, your own modules and __name__.',
    ['import', 'module', 'from ', '__name__', '__main__', 'math.', 'random.', 'standard library', 'alias', ' as ']),
  S('py.packages-environments', 'Packages and environments', 'foundations', ['py.modules'],
    'Packages, pip, virtual environments and organising a project.',
    ['pip', 'package', 'venv', 'virtual environment', '__init__', 'requirements', 'install']),
  S('py.classes-objects', 'Classes and objects', 'foundations', ['py.functions', 'py.dictionaries'],
    'Defining classes, __init__, self, instances, attributes and methods.',
    ['class', '__init__', 'self', 'object', 'instance', 'method', 'attribute']),
  S('py.class-design', 'Class attributes and encapsulation', 'foundations', ['py.classes-objects'],
    'Class variables, class and static methods, and access conventions.',
    ['class variable', 'classmethod', 'staticmethod', '@', 'encapsulat', 'private', '_', 'property', 'cls']),
  S('py.inheritance', 'Inheritance and polymorphism', 'foundations', ['py.class-design'],
    'Subclasses, overriding, super() and polymorphism.',
    ['inherit', 'subclass', 'super(', 'override', 'polymorph', 'parent', 'child', 'isinstance']),
  S('py.files', 'Reading and writing files', 'foundations', ['py.for-loops'],
    'open, modes, reading and writing text, and the with statement.',
    ['open(', 'read(', 'readline', 'write(', 'with ', 'file', '"r"', '"w"', '"a"', 'close']),
  S('py.file-paths', 'File paths', 'foundations', ['py.files'],
    'Relative and absolute paths, os.path and pathlib.',
    ['path', 'pathlib', 'os.path', 'directory', 'folder', 'filenotfounderror', 'absolute', 'relative']),
  S('py.exceptions', 'Exceptions and handling them', 'foundations', ['py.conditionals', 'py.functions'],
    'Exception types, try/except/else/finally, raising and custom exceptions.',
    ['try', 'except', 'raise', 'finally', 'exception', 'error', 'traceback']),
  S('py.debugging', 'Debugging', 'foundations', ['py.exceptions'],
    'Reading tracebacks, print debugging, debuggers and logical errors.',
    ['debug', 'traceback', 'breakpoint', 'pdb', 'logic error', 'logical error', 'bug', 'print statement']),
  S('py.testing', 'Testing', 'foundations', ['py.exceptions', 'py.parameters-return'],
    'assert, unittest, test-driven development and code quality.',
    ['test', 'assert', 'unittest', 'tdd', 'edge case', 'pytest', 'quality', 'lint']),
  S('py.recursion', 'Recursion and decomposition', 'foundations', ['py.parameters-return', 'py.conditionals'],
    'Base cases, recursive calls, and breaking a problem into parts.',
    ['recurs', 'base case', 'factorial', 'fibonacci', 'recursionerror', 'decompos']),
  S('py.json-apis', 'JSON, APIs and file formats', 'foundations', ['py.dictionaries', 'py.files'],
    'json.loads/dumps, CSV and other formats, and fetching data from an API.',
    ['json', 'api', 'request', 'csv', 'loads', 'dumps', 'format', 'http', 'endpoint', 'external librar']),
  S('py.efficiency', 'Efficiency and Big O', 'foundations', ['py.loop-control', 'py.lists'],
    'Counting work, Big O for common operations and choosing faster structures.',
    ['big o', 'o(n', 'o(1', 'efficien', 'complexity', 'faster', 'slower', 'linear', 'quadratic']),
  S('py.dates-times', 'Dates and times', 'foundations', ['py.modules'],
    'datetime, date arithmetic with timedelta, and formatting dates.',
    ['datetime', 'timedelta', 'strftime', 'strptime', 'date', 'time']),
  S('py.visualisation', 'Plotting with matplotlib', 'foundations', ['py.modules', 'py.lists'],
    'Line, bar and scatter plots, labels and saving a figure.',
    ['matplotlib', 'plt', 'plot', 'chart', 'axis', 'label', 'figure', 'bar', 'scatter']),
  S('py.automation', 'Automating tasks', 'foundations', ['py.files', 'py.modules'],
    'Scripts that rename, move and process files and run on their own.',
    ['automat', 'os.listdir', 'shutil', 'rename', 'schedule', 'batch', 'glob']),
  S('py.project-work', 'Planning and shipping a project', 'foundations', ['py.functions', 'py.dictionaries', 'py.files', 'py.exceptions'],
    'Planning, structuring, implementing, presenting and reflecting on a project.',
    ['project', 'plan', 'proposal', 'requirement', 'scope', 'feature', 'user', 'present', 'reflect', 'document', 'structure', 'milestone']),

  // ------------------------------------------------------- Python for Data
  S('data.records', 'Tables as lists, records and CSV', 'data', ['py.lists', 'py.dictionaries'],
    'Rows, columns and records in plain Python, and reading CSV with the csv module.',
    ['row', 'column', 'record', 'csv', 'dictreader', 'reader', 'table', 'header']),
  S('data.summaries', 'Summarising numbers', 'data', ['data.records', 'py.arithmetic'],
    'Count, total, mean, median, extremes and what each one hides.',
    ['mean', 'median', 'average', 'sum', 'min', 'max', 'summar', 'spread', 'outlier']),
  S('data.counting-grouping', 'Counting and grouping by hand', 'data', ['data.records'],
    'Counting with dictionaries and Counter, and grouping rows by a key.',
    ['count', 'counter', 'group', 'setdefault', 'frequency', 'most_common']),
  S('data.cleaning', 'Cleaning data', 'data', ['data.records', 'py.exceptions'],
    'Missing values, fixing types, duplicates and normalising text.',
    ['missing', 'blank', 'dirty', 'clean', 'duplicate', 'n/a', 'convert', 'normalis', 'strip', 'fill', 'drop']),
  S('data.filter-sort', 'Filtering and sorting records', 'data', ['data.records', 'py.conditionals'],
    'Selecting rows with conditions, boundaries, sorting and ranking.',
    ['filter', 'sort', 'rank', 'top', 'boundary', '>=', 'key=', 'reverse']),
  S('np.arrays', 'numpy arrays and dtypes', 'data', ['py.indexing-slicing'],
    'Creating arrays, dtypes, shape, indexing and slices as views.',
    ['array', 'dtype', 'shape', 'np.array', 'arange', 'linspace', 'zeros', 'view', 'copy']),
  S('np.vectorised', 'Masks, broadcasting and axes', 'data', ['np.arrays', 'py.booleans'],
    'Boolean masks, element-wise maths, broadcasting and summing along an axis.',
    ['mask', 'broadcast', 'axis', 'np.where', 'vectori', 'element-wise', '&', '|', 'sum(axis']),
  S('pd.dataframes', 'Series and DataFrames', 'data', ['np.arrays', 'py.dictionaries'],
    'Series, building DataFrames, loc and iloc, adding and dropping columns, dtypes.',
    ['series', 'dataframe', 'loc', 'iloc', 'index', 'column', 'drop', 'dtype', 'astype']),
  S('pd.io', 'Getting data in and out with pandas', 'data', ['pd.dataframes', 'data.records'],
    'read_csv options, missing markers, JSON, writing files and checking a load.',
    ['read_csv', 'sep', 'header', 'na_values', 'usecols', 'json', 'to_csv', 'index=false', 'shape', 'info(', 'load']),
  S('pd.filter-derive', 'Filtering and deriving with pandas', 'data', ['pd.dataframes', 'np.vectorised'],
    'Masks over rows, isin/between/query, derived columns, apply, binning and top n.',
    ['isin', 'between', 'query', 'apply', 'cut', 'qcut', 'bin', 'nlargest', 'sort_values', 'derived', 'np.where', 'mask']),
  S('pd.groupby', 'Grouping and aggregating', 'data', ['pd.filter-derive', 'data.counting-grouping'],
    'groupby, size versus count, agg, several keys, transform and pivot tables.',
    ['groupby', 'agg', 'size', 'transform', 'pivot_table', 'split-apply-combine', 'aggregate', 'group']),
  S('pd.combine-reshape', 'Combining and reshaping tables', 'data', ['pd.groupby', 'pd.io'],
    'concat, merge and join types, merge failures, melt and pivot.',
    ['merge', 'join', 'concat', 'melt', 'pivot', 'how=', 'validate', 'key', 'wide', 'long']),
  S('pd.time-series', 'Time series', 'data', ['pd.filter-derive'],
    'Parsing dates, date parts, a datetime index, resample, rolling and change.',
    ['to_datetime', 'date', 'dt.', 'resample', 'rolling', 'diff', 'pct_change', 'shift', 'datetime', 'month', 'window']),
  S('data.reporting', 'Charts and reporting findings', 'data', ['pd.groupby', 'data.summaries'],
    'Choosing a chart, honest labels, formatting numbers, summary tables and write-ups.',
    ['chart', 'label', 'axis', 'format', 'round', 'report', 'finding', 'correlat', 'cause', 'summary table', 'n=']),
];

/* Lesson slug -> skills, per course and unit. The first skill is the lesson's
   primary skill; a unit's primary skills (in lesson order) are the fallback
   pool for an end-of-unit question no keyword matched. */
export const LESSONS = {
  foundations: {
    1: {
      'what-is-python': ['py.running-code'], 'installing-python-ide': ['py.running-code'],
      'first-program': ['py.running-code'], 'syntax-indentation': ['py.syntax'],
      'variables-types': ['py.variables-types'], 'type-io': ['py.input-conversion'],
      'comments-docs': ['py.syntax', 'py.documentation'], 'arithmetic-expressions': ['py.arithmetic'],
    },
    2: {
      'understanding-control-flow': ['py.conditionals'], 'comparison-logical-operators': ['py.booleans'],
      'if-statement': ['py.conditionals'], 'if-else-elif': ['py.conditionals'],
      'nested-conditionals': ['py.conditionals', 'py.booleans'], 'boolean-logic-practice': ['py.booleans'],
      'introduction-loops': ['py.while-loops', 'py.for-loops'], 'while-loop': ['py.while-loops'],
      'for-loop': ['py.for-loops'], 'loop-control-statements': ['py.loop-control'],
      'practical-control-flow-examples': ['py.loop-control', 'py.conditionals'],
    },
    3: {
      'what-are-functions': ['py.functions'], 'defining-calling-functions': ['py.functions'],
      'parameters-arguments': ['py.parameters-return'], 'return-statements': ['py.parameters-return'],
      'variable-scope-lifetime': ['py.scope'], 'default-optional-parameters': ['py.parameters-return'],
      'docstrings-documentation': ['py.documentation'], 'nested-helper-functions': ['py.scope'],
      'lambda-functions': ['py.lambdas'], 'practical-function-examples': ['py.parameters-return', 'py.functions'],
    },
    4: {
      'introduction-data-structures': ['py.lists'], 'lists-operations': ['py.lists'],
      'indexing-slicing-lists': ['py.indexing-slicing'], 'nested-lists-2d': ['py.indexing-slicing'],
      'tuples-immutable': ['py.tuples-sets'], 'dictionaries-key-value': ['py.dictionaries'],
      'dictionary-methods-iteration': ['py.dictionaries'], 'sets-unique-collections': ['py.tuples-sets'],
      'copying-comparing-structures': ['py.mutability'], 'choosing-right-structure': ['py.mutability'],
    },
    5: {
      'what-are-modules': ['py.modules'], 'importing-builtin-modules': ['py.modules'],
      'creating-your-own-modules': ['py.modules'], 'name-main-pattern': ['py.modules'],
      'working-with-packages': ['py.packages-environments'], 'python-standard-library': ['py.modules'],
      'installing-external-packages': ['py.packages-environments'], 'virtual-environments': ['py.packages-environments'],
      'module-aliases-selective-imports': ['py.modules'], 'project-organization-best-practices': ['py.packages-environments'],
    },
    6: {
      'introduction-oop-concepts': ['py.classes-objects'], 'defining-creating-classes': ['py.classes-objects'],
      'creating-using-objects': ['py.classes-objects'], 'instance-variables-methods': ['py.classes-objects'],
      'class-variables-class-methods': ['py.class-design'], 'encapsulation-access-control': ['py.class-design'],
      'inheritance-subclasses': ['py.inheritance'], 'polymorphism-method-overriding': ['py.inheritance'],
      'super-function': ['py.inheritance'], 'oop-real-projects': ['py.inheritance', 'py.class-design'],
    },
    7: {
      'introduction-file-handling': ['py.files'], 'opening-closing-files': ['py.files'],
      'reading-data-from-files': ['py.files'], 'writing-data-to-files': ['py.files'],
      'working-with-file-paths': ['py.file-paths'], 'with-statement-file-operations': ['py.files'],
      'understanding-errors-exceptions': ['py.exceptions'], 'try-except-blocks': ['py.exceptions'],
      'raising-customizing-exceptions': ['py.exceptions'], 'file-error-handling-real-projects': ['py.exceptions', 'py.files'],
    },
    8: {
      'what-is-debugging': ['py.debugging'], 'common-types-errors': ['py.debugging', 'py.exceptions'],
      'print-statements-debugging': ['py.debugging'], 'breakpoints-debuggers': ['py.debugging'],
      'understanding-tracebacks': ['py.debugging'], 'writing-running-tests': ['py.testing'],
      'introduction-unittest': ['py.testing'], 'test-driven-development': ['py.testing'],
      'debugging-logical-runtime-errors': ['py.debugging'], 'maintaining-code-quality': ['py.testing'],
    },
    9: {
      'recursion-problem-decomposition': ['py.recursion'], 'working-with-external-libraries': ['py.json-apis', 'py.packages-environments'],
      'apis-data-retrieval': ['py.json-apis'], 'introduction-json-data-parsing': ['py.json-apis'],
      'efficiency-big-o-basics': ['py.efficiency'], 'working-with-dates-times': ['py.dates-times'],
      'data-visualization-matplotlib': ['py.visualisation'], 'basic-automation-python': ['py.automation'],
      'introduction-file-formats': ['py.json-apis'], 'applying-advanced-concepts': ['py.recursion', 'py.json-apis'],
    },
    10: {
      'project-planning-brainstorming': ['py.project-work'], 'writing-project-proposal': ['py.project-work'],
      'structuring-python-project': ['py.project-work', 'py.modules'], 'implementing-core-features': ['py.project-work', 'py.functions'],
      'adding-user-interaction': ['py.project-work', 'py.input-conversion'], 'error-handling-testing-code': ['py.project-work', 'py.testing'],
      'polishing-visuals-output-formatting': ['py.project-work', 'py.input-conversion'], 'writing-documentation-comments': ['py.project-work', 'py.documentation'],
      'presenting-your-project': ['py.project-work'], 'reflection-next-steps': ['py.project-work'],
    },
  },
  data: {
    1: {
      'what-is-data-analysis': ['data.records'], 'rows-and-columns-with-lists': ['data.records'],
      'records-as-dictionaries': ['data.records'], 'reading-a-csv-file': ['data.records'],
      'summarising-numbers': ['data.summaries'], 'counting-and-grouping': ['data.counting-grouping'],
    },
    2: {
      'what-dirty-data-looks-like': ['data.cleaning'], 'missing-values': ['data.cleaning'],
      'fixing-types': ['data.cleaning'], 'removing-duplicates': ['data.cleaning'],
      'filtering-rows': ['data.filter-sort'], 'sorting-and-ranking': ['data.filter-sort'],
    },
    3: {
      'why-arrays-beat-lists': ['np.arrays'], 'creating-arrays-and-dtypes': ['np.arrays'],
      'indexing-and-slicing-arrays': ['np.arrays'], 'boolean-masks': ['np.vectorised'],
      'array-maths-and-broadcasting': ['np.vectorised'], 'summing-and-axes': ['np.vectorised'],
    },
    4: {
      'the-series': ['pd.dataframes'], 'building-a-dataframe': ['pd.dataframes'],
      'selecting-columns-and-rows': ['pd.dataframes'], 'adding-and-dropping-columns': ['pd.dataframes'],
      'dtypes-in-pandas': ['pd.dataframes'], 'reading-a-csv-into-pandas': ['pd.io', 'pd.dataframes'],
    },
    5: {
      'csv-options-that-matter': ['pd.io'], 'missing-markers-on-load': ['pd.io', 'data.cleaning'],
      'selecting-what-you-need': ['pd.io'], 'reading-json-data': ['pd.io'],
      'writing-data-out': ['pd.io'], 'checking-what-you-loaded': ['pd.io'],
    },
    6: {
      'filtering-with-masks': ['pd.filter-derive'], 'isin-between-and-query': ['pd.filter-derive'],
      'derived-columns': ['pd.filter-derive'], 'apply-and-when-not-to': ['pd.filter-derive'],
      'binning-values': ['pd.filter-derive'], 'sorting-and-top-n': ['pd.filter-derive'],
    },
    7: {
      'split-apply-combine': ['pd.groupby'], 'counting-groups': ['pd.groupby'],
      'agg-with-several-summaries': ['pd.groupby'], 'grouping-by-several-keys': ['pd.groupby'],
      'transform-versus-aggregate': ['pd.groupby'], 'pivot-tables': ['pd.groupby', 'pd.combine-reshape'],
    },
    8: {
      'concat-stacking-tables': ['pd.combine-reshape'], 'merging-on-a-key': ['pd.combine-reshape'],
      'when-a-merge-goes-wrong': ['pd.combine-reshape'], 'wide-to-long-with-melt': ['pd.combine-reshape'],
      'long-to-wide-with-pivot': ['pd.combine-reshape'], 'putting-a-join-to-work': ['pd.combine-reshape', 'pd.io'],
    },
    9: {
      'parsing-dates': ['pd.time-series'], 'date-parts': ['pd.time-series'],
      'a-datetime-index': ['pd.time-series'], 'resampling': ['pd.time-series'],
      'rolling-windows': ['pd.time-series'], 'change-over-time': ['pd.time-series'],
    },
    10: {
      'choosing-a-chart': ['data.reporting'], 'labels-and-honesty': ['data.reporting'],
      'formatting-numbers': ['data.reporting'], 'a-summary-table': ['data.reporting', 'pd.groupby'],
      'writing-up-a-finding': ['data.reporting'], 'the-whole-analysis': ['data.reporting', 'pd.combine-reshape'],
    },
  },
};

/* Hand corrections to keyword tags on end-of-unit items, found by reviewing a
   random sample. Recorded as source 'override'. Add to this when a tag is
   wrong rather than bending a skill's keywords to fit one question. */
export const TAG_OVERRIDES = {
  'mcq:u1-m50': ['py.syntax', 'py.documentation'],   // which comment is most useful
  'mcq:u3-m28': ['py.scope'],                        // a nested function's reach
  'mcq:u10-m11': ['py.testing', 'py.input-conversion'], // try/except around int()
};
